# Generated by Django 2.2.4 on 2019-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('startH', models.TimeField()),
                ('endH', models.TimeField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
    ]
